### ISSUE TITLE
Code can't work

### ISSUE THREAD

**Issue by iseesaw** [morning-dews/GSN-Dialogues#3]
While I run the code, it just stop after "build the graph"...

**Comment by iseesaw** [comment]
Oh, it's my mistake
your data file name should be train_0.json eval_0.json
otherwise, it will hang on batch_queue.get()
Maybe it should be batch_queue.get(block=False), then it will raise a empty exception

**Comment by smileSQSQ** [comment]
> Oh, it's my mistake
> your data file name should be train_0.json eval_0.json
> otherwise, it will hang on batch_queue.get()
> Maybe it should be batch_queue.get(block=False), then it will raise a empty exception



> Oh, it's my mistake
> your data file name should be train_0.json eval_0.json
> otherwise, it will hang on batch_queue.get()
> Maybe it should be batch_queue.get(block=False), then it will raise a empty exception

老哥能不能说一下数据集是怎么准备的，作者给出的例子，后三项是什么意思
For example:
{
    "context": ["you do n't get a window with gears ?", "i do get glxgears EMOJI but no display of fps EMOJI", "should show in the terminal", "make that , yes there are EMOJI", "no reason to kick 'em .", "google for ur question theres a site about that somewhere , u need wine and mozilla-controls", "what do you need exactly ?"], 
    "answer": "depends - this is quite a large chan - and apokryphos did n't ban , just remoed", 
    "ans_idx": 4, 
    "relation_at": [[1, 0], [2, 1], [3, 2], [4, 2], [5, 4], [6, 5]], 
    "relation_user": [[2, 0]]
}
